name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run commands
        run: |
          ls -la
          pwd
          
      - name: Build the Docker image
        run: docker build --tag python-webapp:$(date +%s) --file proj/Dockerfile .
        
      - name: Check docker image
        run: docker images
