name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run commands
        run: |
          ls -la
          pwd
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build the Docker image
        id: build-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: esc-repo
          IMAGE_TAG: python-webapp:$(date +%s)
        run: |
          docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_TAG --file proj/Dockerfile proj/.
          # docker build --tag python-webapp:$(date +%s) --file proj/Dockerfile proj/.
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_TAG
          echo "::set-output name-image::$ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_TAG"
        
      - name: Check docker image
        run: docker images | grep python-webapp
        
      - name: Docker Push
        
